site_description: Jbone - Spring Cloud综合应用实践和基础开发框架
site_keywords : jbone,Spring Cloud,sso,微服务
google_analytics: UA-46852172-3
root_domain: doc.jbone.cn
vue_version: 2.5.16

platinum_sponsors_china:
  - url:
    img:
video_sponsors_china:
  - url:
    img:
special_sponsors:
  - url:
    img:
    description:
platinum_sponsors:
  - url:
    img:
    name:
gold_sponsors:
  - url:
    img:
    name:
silver_sponsors:
  - url:
    img:
    name:
bronze_sponsors:
  - url:
    img:
    name:
